import 'jquery'
import './init'
import '/imports/material-js/bootstrap-material-design.min'
import '/imports/plugins/perfect-scrollbar.jquery.min'
import '/imports/material-js/material-dashboard'

import '../imports/ui/blank/blank'
import '../imports/ui/dashboard/dashboard'
import '../imports/ui/icons/icons'
import '../imports/ui/maps/maps'
import '../imports/ui/notifications/notifications'
import '../imports/ui/tables/tables'
import '../imports/ui/typography/typography'
import '../imports/ui/upgrade/upgrade'
import '../imports/ui/user/user'